version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: datatg_postgres
    restart: always
    environment:
      POSTGRES_DB: tgwarehouse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123321
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

volumes:
  pgdata:
